apiVersion: v2
name: argocd-apps-wrapper
description: A Helm chart to wrap argocd-apps ArgoCD application.
type: application
version: 0.1.0
appVersion: "v2.0.0"

dependencies:
  - name: argocd-apps
    version: "2.0.2"
    repository: "https://argoproj.github.io/argo-helm"