{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "torchserve.fullname" . }}
  labels:
    {{- include "torchserve.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "torchserve.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    {{- if .Values.networkPolicy.egress }}
    - Egress
    {{- end }}
  ingress:
    - ports:
        - protocol: TCP
          port: {{ .Values.torchserve.config.inferencePort }}
        - protocol: TCP
          port: {{ .Values.torchserve.config.managementPort }}
        - protocol: TCP
          port: {{ .Values.torchserve.config.metricsPort }}
    {{- with .Values.networkPolicy.ingress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.networkPolicy.egress }}
  egress:
    {{- with .Values.networkPolicy.egress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
