apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: nginx
      volumeMounts:
        - name: my-storage-volume
          mountPath: "/data"
  volumes:
    - name: my-storage-volume
      persistentVolumeClaim:
        claimName: test-pvc